const strings = {
    income: "Priliv:",
    expenses: "Troskovi:",
    available: "Raspolozivo:",
    transNameLabel: "Naziv unosa:",
    transAmountLabel: "Iznos:",
    isReocuring: "Trosak je jednokratan:",
    expDate: "Istice:",
    startDate: "Racuna se od:",
    monOrYear: "Obracunava se:",
    type: "Unos je:",
    incomeList: "Lista prihoda:",
    expenseList: "Lista troskova:",
    noExpDate: "Trajni unos:",
    transNamePlaceholder: "Plata",
    transAmountPlaceholder: "100000",
    currenthMonthTotals: "Obracun za tekuci mesec:",
    selectedMonth: "Izabrani mesec:",
    entryTitle: "Unos:",
    occurenceOption1: "Mesecno",
    occurenceOption2: "Godisnje",
    typeOption1: "Prihod",
    typeOption2: "Trosak",
    folderTab1: "Unosi",
    folderTab2: "Godisnje",
    folderButton3: "Mesecni Prikaz",
    folderButton4: "Stednja",
    projectionTitle: "Godisnji prikaz:",
    months: ["Januar:", "Februar:", "Mart:", "April:", "Maj:", "Jun:", "Jul:", "Avgust:", "Septembar:", "Oktobar:", 'Novembar:', "Decembar:"],
    placeholderName: "Plata",
    placeholderAmount: "1000", 
}

export default strings